name: Release

on:
  push:
    tags:
      - 'v*' # Trigger only on tags that start with v

permissions:
  contents: write

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true
          cache-dependency-path: 'src/go.sum'

      - name: Build Binary
        run: |
          cd src
          output_name=bmh-${{ matrix.goos }}-${{ matrix.goarch }}
          if [ "${{ matrix.goos }}" = "windows" ]; then
            output_name=${output_name}.exe
          fi
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -ldflags="-s -w" -o ../$output_name ./main.go

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: bmh-${{ matrix.goos }}-${{ matrix.goarch }}*
